### ISSUE TITLE
App\Nova\Note not found.

### ISSUE THREAD

**Issue by Milkhan** [DigitalCloud/nova-resource-notes#1]
Very nice package thank you. But Ive encounter a small problem. 
When you add notes to a resource it searches for App\Nova\Note and I added it manually. 
And a feature request:
I've just Any chance if we can see the **timestamps** on the notes?
Thank you very much.

**Comment by devmtm** [comment]
I just add the user and timestamp for the note. But i don't understand your point: When you add notes to a resource it searches for App\Nova\Note and I added it manually. Can you explain?

**Comment by Yelles** [comment]
if you forget to import `DigitalCloud\NovaResourceNotes\Fields\Notes` in your nova ressource, it will ask for `App\Nova\Note`, may be it's the point ?

**Comment by devmtm** [comment]
@Milkhan Can you please confirm that this issue still, and please provide more detail, otherwise i will close it.
thanks.

**Comment by Yelles** [comment]
@devmtm working as expected for me

**Comment by Milkhan** [comment]
@devmtm Thank you very much for the timestamps and Im sorry I didnt get a notification about your mention, I just saw it. The previous problem indeed was as @Yelles  mentioned I forgot to import the class. All is good now.  Thank you again!

**Comment by Milkhan** [comment]
@devmtm In case its my mistake I dint open a new issue, but I couldnt see the neither timestamp nor user name. I've update to 1.4 , composer update, made cache:clear but still I cant see the changes. Is it my mistake somewhere? Thank you.
