### ISSUE TITLE
Error when Application Namespace is not `App\`

### ISSUE THREAD

**Issue by phikhi** [DigitalCloud/nova-resource-notes#10]
If your application has a changed namespace (change made with `php artisan app:name {NewNamespace}` )

An error is thrown because, `nova-resource-notes/src/Resources/Note.php` uses the `App\Nova\Resource`. And the `App\` does not exist anymore. It should use `NewNamespace\Nova\Resource` instead.

Maybe we could publish a configuration file to dynamically target the `Resource` class we need to extend ?

**Comment by chrisneal** [comment]
You need to change this in the laravel-blameable config.

https://github.com/DigitalCloud/laravel-blameable

**Comment by phikhi** [comment]
Got it, thanks ;)

**Comment by izi-dev** [comment]
I have this error, I have not been able to solve it.
