### ISSUE TITLE
User Avatar missing

### ISSUE THREAD

**Issue by Yelles** [DigitalCloud/nova-resource-notes#3]
Hi,

Many thanks for your work, it's very useful !

Any idea why my avatar (local file, not gravatar) is not displayed ? Or how to specify which one to use ?

<img width="339" alt="cleanshot 2019-01-28 at 16 38 30 2x" src="https://user-images.githubusercontent.com/689478/51847440-fc919800-231b-11e9-8acd-0d57a04b1edb.png">

ps: really like the new design !

**Comment by devmsh** [comment]
@Yelles the avatar is not displayed only in the notes section? or in the whole system? please provide us with more information.

**Comment by Yelles** [comment]
@devmsh sorry for the lack of information...

you are right, i had to update the user blade file (for viewing the avatar in the nova header): **/resources/views/vendor/nova/partials/user.blade.php**

from : 
`...`
`<img src="https://secure.gravatar.com/avatar/{{ md5($user->email) }}?size=512" class="rounded-full w-8 h-8 mr-3"/>`
`...`

to : 

`...`
`@if(isset(auth()->user()->avatar))`
`        <img src="/storage/{{ auth()->user()->avatar }}" class="rounded-full w-8 h-8 mr-3"/>`
`    @else`
`        <img src="https://secure.gravatar.com/avatar/{{ md5($user->email) }}?size=512" class="rounded-full w-8 h-8 mr-3"/>`
`    @endif`
`...`

(Since users have an Avatar field, it's working out of the box in the search for example : https://nova.laravel.com/docs/1.0/resources/fields.html#avatar-field)

**Comment by Yelles** [comment]
Is there a way to do same with your component ?

**Comment by devmtm** [comment]
I already implement it in my component. Just composer update to the new version.

**Comment by Yelles** [comment]
Oh great ! Many thanks

**Comment by devmtm** [comment]
You are welcome.
