### ISSUE TITLE
Issue in JS after installation

### ISSUE THREAD

**Issue by vittoriodev** [DigitalCloud/nova-resource-notes#4]
hi, following issue occurs:
vendor.js:107794 [Vue warn]: Property or method "actionExecuted" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.

and
`[Vue warn]: Invalid handler for event "actionExecuted": got undefined

found in

---> at resources/js/components/NotesWrapper.vue
at resources/js/components/DetailField.vue
at resources/js/components/Detail/RelationshipPanel.vue
at resources/js/components/LoadingView.vue
at resources/js/views/Detail.vue
`

and more. Whats wrong? Installed like described to nova 1.3.1

**Comment by devmtm** [comment]
Merge pull request #6 from cierrateam/master 
Thank you for your contributions.
